plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.2'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.notification'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

jar {
    manifest {
        attributes(
                'Main-Class': 'com.notification.service.NotificationApplication'
        )
    }
}


configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa:3.4.2'
    implementation 'org.springframework.boot:spring-boot-starter-web:3.4.2'

    implementation 'org.telegram:telegrambots-spring-boot-starter:6.9.7.1'
    implementation 'org.telegram:telegrambots:6.9.7.1'
    implementation 'org.telegram:telegrambots-abilities:6.9.7.1'

    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.3.0'

    implementation 'org.flywaydb:flyway-core:10.10.0'
    implementation 'org.flywaydb:flyway-database-postgresql:10.10.0'

    implementation 'org.mapstruct:mapstruct:1.5.5.Final'
    implementation 'org.projectlombok:lombok-mapstruct-binding:0.2.0'

    annotationProcessor 'org.projectlombok:lombok:1.18.36'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'

    compileOnly 'org.projectlombok:lombok:1.18.36'

    runtimeOnly 'org.postgresql:postgresql:42.7.5'

    testImplementation 'org.springframework.boot:spring-boot-starter-test:3.4.2'
    testAnnotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.11.4'
}

tasks.named('test') {
    useJUnitPlatform()
}
