name: telegram-bot-notification
version: '3.8'

services:
  notification-service:
    build:
      context: ..
      dockerfile: ./deployment/Dockerfile
    ports:
      - "9095:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://telegram-bot-data:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - telegram-bot-data
    env_file:
      - docker.compose.env

  telegram-bot-data:
    image: postgres:latest
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - docker.compose.env

volumes:
  db_data: