CREATE TYPE task_status AS ENUM ('OPEN', 'IN_PROGRESS', 'CLOSED', 'REVIEW', 'NEED_INFORMATION', 'NEED_FIXES');

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    link_to_mr VARCHAR(255) NOT NULL,
    status task_status,
    developer_id BIGINT,
    reviewer_id BIGINT
)