CREATE TABLE users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username  VARCHAR(255) NOT NULL,
    gitlab_id VARCHAR(255) NOT NULL,
    role      VARCHAR(255) NOT NULL
);

CREATE TABLE tasks
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(255) NOT NULL,
    link_to_mr   VARCHAR(255) NOT NULL,
    status       VARCHAR(255) NOT NULL,
    developer_id BIGINT       NOT NULL,
    reviewer_id  BIGINT       NOT NULL,
    FOREIGN KEY (developer_id) REFERENCES users (id),
    FOREIGN KEY (reviewer_id) REFERENCES users (id)
);